// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAV7_t7Zn1XQKf6zyTxSezwJu6ixQMUMfA',
    appId: '1:964776840761:web:3afa56f5d23fc93708c7e8',
    messagingSenderId: '964776840761',
    projectId: 'note-c50c0',
    authDomain: 'note-c50c0.firebaseapp.com',
    storageBucket: 'note-c50c0.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBrWQcT_3fw66kxejgSOP0cm45eMixqJKc',
    appId: '1:964776840761:android:4055d14b48012fc808c7e8',
    messagingSenderId: '964776840761',
    projectId: 'note-c50c0',
    storageBucket: 'note-c50c0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBKebuSz2XSd-IJ2vYIO4tTBCfymkJQXm4',
    appId: '1:964776840761:ios:e9acfdfbb1477eb508c7e8',
    messagingSenderId: '964776840761',
    projectId: 'note-c50c0',
    storageBucket: 'note-c50c0.appspot.com',
    iosClientId: '964776840761-nuqauj4fbls0ogfr1k06h1g78c3enqhg.apps.googleusercontent.com',
    iosBundleId: 'com.example.test',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBKebuSz2XSd-IJ2vYIO4tTBCfymkJQXm4',
    appId: '1:964776840761:ios:e9acfdfbb1477eb508c7e8',
    messagingSenderId: '964776840761',
    projectId: 'note-c50c0',
    storageBucket: 'note-c50c0.appspot.com',
    iosClientId: '964776840761-nuqauj4fbls0ogfr1k06h1g78c3enqhg.apps.googleusercontent.com',
    iosBundleId: 'com.example.test',
  );
}
